spring: 
  profiles: 
    active: "local"
---

#공통
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        same-site: strict
      timeout: 30m

# 파일 업로드 경로
file:
  upload:
    path: C:/Users/mirag/uploads

#logging:
#  level:
#    com.infraReport: DEBUG
#    org.mybatis: DEBUG
#    org.springframework.jdbc: DEBUG
#    org.springframework.security: DEBUG

---

#로컬
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/daily_report_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml

---

#운영
server:
  port: 80

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/daily_report_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
